### ISSUE TITLE
StreamClient Append Message Issue

### ISSUE THREAD

**Issue by shravan097** [aws/aws-greengrass-core-sdk-python#7]
I am trying to append a message to the Stream but I am getting this error `ERROR:StreamManagerClient:Unable to read from socket, likely socket is closed or server died` but I am able to create streams without any error.  Digging deep into the stream logs, I see that Stream manager cannot deserialize the instance of byte[]. Please see the GGStreamManager.log excerpt below.

```
[2020-01-27T14:54:03.267-08:00][ERROR]- (nioEventLoopGroup-3-3) com.amazonaws.iot.greengrass.streammanager.server.handlers.MessageStreamHandler: Caught exception in MessageStreamHandler
[2020-01-27T14:54:03.267-08:00][ERROR]-com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `byte[]` out of VALUE_STRING token
[2020-01-27T14:54:03.267-08:00][ERROR]- at [Source: (io.netty.buffer.ByteBufInputStream); line: -1, column: 73] (through reference chain: com.amazonaws.greengrass.streammanager.protocol.AppendMessageRequest["payload"])
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers.handleNonArray(PrimitiveArrayDeserializers.java:240) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$ByteDeser.deserialize(PrimitiveArrayDeserializers.java:498) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$ByteDeser.deserialize(PrimitiveArrayDeserializers.java:446) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3071) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.amazonaws.greengrass.streammanager.protocol.SerDesUtil.deserialize(SerDesUtil.java:65) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.267-08:00][ERROR]-	at com.amazonaws.iot.greengrass.streammanager.server.handlers.MessageStreamHandler.channelRead(MessageStreamHandler.java:95) ~[AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [AWSGreengrassStreamManager.jar:?]
[2020-01-27T14:54:03.268-08:00][ERROR]-	at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by MikeDombo** [comment]
Hi, 
It looks like you're not passing a `bytes` object when you call `appendMessage`. Based on the error, it looks like you're trying to append a string which will not work. What you need to do is encode the string to bytes. You can accomplish this like `"somestring".encode("utf-8")`, which will output `bytes`.

**Comment by shravan097** [comment]
@MikeDombo  Thanx for noticing that. Encoding it fixed my issue.
